export { default as DashboardPage } from './Dashboard'
export { default as GamePage } from './Game'
export { default as AboutMePage } from './AboutMe'
export { default as PetsPage } from './pets'
export { default as PetDetailPage } from './PetDetail'
export { default as NotFoundPage } from './NotFound'
export { default as FavoritesPage } from './Favorites'
